### ISSUE TITLE
2022-09-30 - Helping Your Team Understand and Form OKRs

### ISSUE THREAD

**Issue by phazonoverload** [yougotthisconf/yougotthis.io#18]

**Comment by stevenjmesser** [comment]
Are you looking for contributors for this?

**Comment by phazonoverload** [comment]
No, sorry, I’ll pad out these issues today. This is scheduled content already written

**Comment by phazonoverload** [comment]
But please do check out the hacktoberfest labelled issues for some ways to get involved.
