### ISSUE TITLE
Add summaries for You Got This Summer 2021 videos

### ISSUE THREAD

**Issue by phazonoverload** [yougotthisconf/yougotthis.io#33]
[Add summaries](https://github.com/yougotthisconf/yougotthis.io/blob/main/.github/CONTRIBUTING.md#content-summaries) to all videos in `/content/library/videos/summer-2021`

**Comment by harshitajain165** [comment]
Hey @phazonoverload, can I work on this one as well?

**Comment by phazonoverload** [comment]
It’s yours!
