### ISSUE TITLE
Add summaries for You Got This Summer 2022 videos

### ISSUE THREAD

**Issue by phazonoverload** [yougotthisconf/yougotthis.io#34]
[Add summaries](https://github.com/yougotthisconf/yougotthis.io/blob/main/.github/CONTRIBUTING.md#content-summaries) to all videos in `/content/library/videos/summer-2022`

**Comment by harshitajain165** [comment]
Hey @phazonoverload 
I'd like to work on this issue as a part of my Hacktoberfest contribution. Would be glad if I could be assigned the same.

**Comment by phazonoverload** [comment]
Yes that’d be great, thanks.
